"""empty message

Revision ID: 3b25e13c81bf
Revises: None
Create Date: 2016-09-05 03:49:24.307374

"""

# revision identifiers, used by Alembic.
revision = '3b25e13c81bf'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outputs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inputs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cmd', sa.String(length=1024), nullable=True),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('output_id', sa.BigInteger(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['output_id'], ['outputs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inputs_created'), 'inputs', ['created'], unique=False)
    op.create_index(op.f('ix_inputs_username'), 'inputs', ['username'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inputs_username'), table_name='inputs')
    op.drop_index(op.f('ix_inputs_created'), table_name='inputs')
    op.drop_table('inputs')
    op.drop_table('outputs')
    ### end Alembic commands ###
