"""empty message

Revision ID: ad05a8ee42fc
Revises: None
Create Date: 2016-08-28 19:10:50.806262

"""

# revision identifiers, used by Alembic.
revision = 'ad05a8ee42fc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inputs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cmd', sa.String(length=1024), nullable=True),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inputs_created'), 'inputs', ['created'], unique=False)
    op.create_index(op.f('ix_inputs_username'), 'inputs', ['username'], unique=False)
    op.create_table('outputs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('input_id', sa.BigInteger(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['input_id'], ['inputs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outputs')
    op.drop_index(op.f('ix_inputs_username'), table_name='inputs')
    op.drop_index(op.f('ix_inputs_created'), table_name='inputs')
    op.drop_table('inputs')
    ### end Alembic commands ###
